Update workflow to use GitHub env

diff --git a/.github/workflows/pa11y-accessibility.yml b/.github/workflows/pa11y-accessibility.yml
--- a/.github/workflows/pa11y-accessibility.yml
+++ b/.github/workflows/pa11y-accessibility.yml
@@ -45,10 +45,11 @@ jobs:
           sleep 10
       - name: Run pa11y
         run: |
-          npx pa11y http://localhost:4173 --config=pa11y-config.json || true
+          output=$(npx pa11y http://localhost:4173 --config=pa11y-config.json || true)
+          echo "PA11Y_OUTPUT=$output" >> $GITHUB_ENV
       - name: Check for accessibility violations and fail the workflow if found
         run: |
-          if echo "${{ steps.pa11y.outputs.pa11y_output }}" | grep -q "Error:"; then
+          if echo "${{ env.PA11Y_OUTPUT }}" | grep -q "Error:"; then
             echo "Accessibility violations found!"
             exit 1
           else
